image: Visual Studio 2017
configuration: Release
environment:
  keystore-password:
    secure: RTlsGiH2xsMnw1X/3addQWtrYzwDAwIO9eY69ObqrUs=
before_build:
- cmd: nuget restore RaidCalculator.sln
build:
  project: RaidCalculator.sln
build_script:
  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "/p:AndroidKeyStore=true" "/p:AndroidSigningKeyAlias=RaidCalculator" "/p:AndroidSigningKeyPass=%keystore-password%" "/p:AndroidSigningKeyStore=RaidCalculator.keystore" "/p:AndroidSigningStorePass=%keystore-password%" "./src/RaidCalculator.Android/RaidCalculator.Android.csproj"
artifacts:
  - path: src\RaidCalculator.Android\bin\Release\one.malz.raidcalculator-Signed.apk
test: off
branches:
  only:
  - master